### PR TITLE
Update README with how to run tests

### PR DESCRIPTION
**Pull request by iUnknwn**
Added instructions on how to run the included unit tests, and the
necessary work arounds to run the tests on Windows.

### CODE REVIEW

**Comment by mchinen** [comment]
Hi @iUnknwn thanks for the PR!  Before we can merge it you'll have to take a look at the CLA and sign it if you agree.  If you don't want to do that, feel free to close the PR.

**Comment by iUnknwn** [comment]
@mchinen - Sorry for the delay - am working with my employer to confirm the rules on CLAs, but I hopefully will have an all clearly shortly. If not, I'll close the PR.

**Comment by mchinen** [comment]
No problem, thanks for the update.

**Comment by iUnknwn** [comment]
@mchinen Hi there - just wanted to touch base on this and ask if there was anything else you needed.

**Comment by mchinen** [comment]
@iUnknwn Thanks for the ping.  Merging now.

**Pull request merged**
