### PR TITLE
Simple python bindings implementation

### PR DESCRIPTION
**Pull request by yuribondarenko**
Hi guys,
I know you've been working on adding python bindings for some time now. I've implemented naive python bindings to the library. Could you please check it out?
Currently, it works only on Linux. I had issues with building third-party dependencies for Windows. At least, pybind11_bazel creates only shared libraries.

### CODE REVIEW

**Comment by mchinen** [comment]
Hi, thanks so much for the PR.  It seems immediately useful.  
Our pybind11 implementation will build on the existing broken pybind11 APIs (they are already in use interally) and will override your changes when it is finally released.  I would recommend to make a new file/module instead of rewriting the existing ones, in case people end up depending on it in the meantime.  That way, we can deprecate it gradually if needed.  The other option is to keep it in a branch that will sit on top of master.  What do you think?

**Comment by yuribondarenko** [comment]
Hey @mchinen. Could you please review it?

**Comment by mchinen** [comment]
Hi @yuribondarenko, sorry I missed your marking of the PR as ready.   I could a) land this on a branch (`working_python`) as is or b) do some style review (https://google.github.io/styleguide/pyguide.html) and land it in master.  We would deprecate your version when our proto-compatible pybind11 changes land which I expect to happen in April (I know this is hugely delayed and my forecasts have been wrong so far, but pybind11 protobuf issues have been resolved upstream, and I have a partially working OSS build now).  Let me know what you would prefer.

**Comment by mchinen** [comment]
Hi @yuribondarenko, just so you know, we have #66 that will land very soon.  It will provide python support through native exposure of some c++ APIs.  We won't want two python APIs, so that will override this PR, (which was helpful in the interim!).  Not sure if there is anything from your PR to merge into the new API after it lands, but let me know if so.

**Pull request closed without merging**
